version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-GL-Project
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gmpp-network

  keycloak:
    image: keycloak-backup
    container_name: GL_Keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak-theme/gmpp:/opt/keycloak/themes/gmpp
    depends_on:
      - postgres
    networks:
      - gmpp-network

volumes:
  postgres_data:

networks:
  gmpp-network:
    driver: bridge
